### ISSUE TITLE
Help with Uncaught exception 'MoorContinueException'

### ISSUE THREAD

**Issue by cosenary** [jeffturcotte/moor#19] opened 2011-11-03 13:11 UTC
<p>My test code:</p>

<pre><code>require_once '../libraries/moor/Moor.php';

class Test extends MoorAbstractController {
  public function helloWorld() {
    echo 'Hello World!';
  }
}

Moor::route('/hello', 'Test::helloWorld');
Moor::run();
</code></pre>

<p>If I call now my <code>/hello</code> route, I always get the following error message:</p>

<pre><code>Fatal error:  Uncaught exception 'MoorContinueException' in /var/www/libraries/moor/Moor.php:674
Stack trace:
#0 /var/www/libraries/moor/Moor.php(1319): Moor::triggerContinue()
#1 /var/www/libraries/moor/Moor.php(840): Moor::validateMethodCallback('Moor::routeNotF...')
#2 /var/www/libraries/moor/Moor.php(628): Moor::dispatchRoute(Object(stdClass))
#3 /var/www/public/routes.php(32): Moor::run()
#4 {main}
  thrown in /var/www/libraries/moor/Moor.php on line 674
</code></pre>

If I add <code>Moor::setNotFoundCallback('Test::notFound');</code> and a <code>notFound()</code> method to my class:

<pre><code>require_once '../libraries/moor/Moor.php';

class Test extends MoorAbstractController {
  public function helloWorld() {
    echo 'Hello World!';
  }
  public function notFound() {
    echo 'Not Found!';
  }
}

Moor::setNotFoundCallback('Test::notFound');
Moor::route('/hello', 'Test::helloWorld');

Moor::run();
</code></pre>

and try to get <code>/hello</code> I always get the <code>Not Found!</code> message.

What I'm doing wrong? Can you give me some advice which helps me to solve the problem?
Many thanks in advance,
Christian

**Comment by mattsah** [comment] 2011-12-04 00:49
what version of PHP are you on?  The uncaught continue exception is caused by the default not found callback not being valid - this is fixed in the dotink fork.  That said the validation code uses reflection which has changed with namespacing etc.  Knowing your version would help to diagnose this.

**Comment by cosenary** [comment] 2011-12-04 11:37
Hello,
thanks for your response. I use PHP version 5.2.17. My hosting company told me that they don't plan to upgrade my account to version 5.3 (shared hosting). Is it possible to get Moor running with my current PHP version?

Kind regards,
Christian

**Comment by mattsah** [comment] 2011-12-04 18:00
@cosenary Try enabling debugging before any calls to Moor and in your not found callback dump out the messages via ::getMessages() and paste that output - it should show where that route is failing.

see the debugging section of the readme file for exact calls

**Comment by cosenary** [comment] 2011-12-04 20:56
I enabled debugging with `Moor::enableDebug();` and tried to get the messages with `Moor::getMessages();`.  
The `var_dump` of this returned an empty array: `array(0) { }` and the Moor::route call returned: `bool(false)`.  
The page is empty and neither a class method nor a function will be called - I've tried both. I haven't also got any PHP errors. Have you got any idea what the error could be?

Thanks for your help so far.

**Comment by mrdamien** [comment] 2012-05-29 22:33
Doesn't sound like a problem in Moor to me, more like some information about the url getting lost.

Can you post your relevant `.htaccess` rewrite rules?
And also what does `var_dump($_SERVER['PATH_INFO'], $_SERVER['REQUEST_URI']);` yield when you visit `/hello`?

**Comment by nickolasnikolic** [comment] 2012-11-23 02:39
I am also having this issue. It is quite a quandry. :-) Thanks in advance for taking a gander, and for any time you offer.

php version 5.3.x
apache version 2.2.22

Here is the call stack:

( ! ) SCREAM: Error suppression ignored for
( ! ) Fatal error: Uncaught exception 'MoorContinueException' in C:\wamp\www\test\PeoplePods\lib\moor\Moor.php on line 674
( ! ) MoorContinueException: in C:\wamp\www\test\PeoplePods\lib\moor\Moor.php on line 674
Call Stack
//  Time    Memory  Function    Location
1   0.0008  804656  {main}( )   ..\index.php:0
2   0.0305  6293408 Moor::run( )    ..\index.php:137
3   0.0310  6296872 Moor::dispatchRoute( )  ..\Moor.php:628
4   0.0311  6297672 Moor::validateMethodCallback( ) ..\Moor.php:840
5   0.0311  6299488 Moor::triggerContinue( )    ..\Moor.php:1319

here is the .htaccess (in the \test\PeoplePods\ directory):

// route non-existant requests to single script
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_URI} !-f
RewriteRule ^.*$ index.php [QSA,NS]

here is the var dump requested in the last post:

( ! ) SCREAM: Error suppression ignored for
( ! ) Notice: Undefined index: PATH_INFO in C:\wamp\www\test\PeoplePods\index.php on line 394
Call Stack
//  Time    Memory  Function    Location
1   0.0008  806328  {main}( )   ..\index.php:0
2   0.0315  6295008 Moor::run( )    ..\index.php:141
3   0.0320  6298424 Moor::dispatchRoute( )  ..\Moor.php:628
4   0.0321  6300192 call_user_func ( )  ..\Moor.php:835
5   0.0321  6300192 default404( )   ..\Moor.php:835
 null
string '/test/PeoplePods/index.php' (length=26)

and finally, the routes:

//get the directory to which we need to send redirects
$siteRoot = $POD->siteInstallRoot( FALSE );

Moor::
    setUrlPrefix( $siteRoot )->
    route("/", "dashboard") -> //needs to go to /PeoplePods/pods/dashboard/index.php    [QSA,L] # core_dashboard
    route("/dashboard", "dashboard") -> //needs to go to /PeoplePods/pods/dashboard/index.php   [QSA,L] # core_dashboard //alius of dashboard
    //the following is a slight modification of dashboard path, but the url is used quite a bit //todo rectify and simplify this following path
    route("/replies", "replies") -> //needs to go to /PeoplePods/pods/dashboard/index.php?replies=1 [QSA,L] # core_dashboard 
    route("/unauthorized", "unauthorized") -> //needs to go to /PeoplePods/pods/unauthorized_landing_page/index.php
    route("/authentication", "authentication") -> //needs to go to
    route("/login", "login") -> //needs to go to /PeoplePods/pods/core_authentication/login.php [QSA,L] # core_authentication_login
    route("/logout", "logout") -> //needs to go to /PeoplePods/pods/core_authentication/logout.php  [QSA,L] # core_authentication_login
    route("/password_reset/:resetCode", "passReset") -> //needs to go to /PeoplePods/pods/core_authentication/password.php?resetCode=$1 [QSA,L] # core_authentication_login
    route("/password_reset", "passReset") -> //needs to go to /PeoplePods/pods/core_authentication/password.php [QSA,L] # core_authentication_login
    route("/join", "joinUs") -> //needs to go to /PeoplePods/pods/core_authentication/join.php  [QSA,L] # core_authentication_creation
    route("/verify", "verify") -> //needs to go to /PeoplePods/pods/core_authentication/verify.php  [QSA,L] # core_authentication_creation
    route("/edit", "edit") -> //needs to go to /PeoplePods/pods/core_usercontent/edit.php   [QSA,L] # contenttype_document_add
    route("/show", "content") -> //needs to go to /PeoplePods/pods/core_usercontent/list.php    [QSA,L] # contenttype_document_list
    route("/show/:stub", "content") -> //needs to go to /PeoplePods/pods/core_usercontent/view.php?stub=$1  [QSA,L] # contenttype_document_view
    route("/files/:id/:size", "files") -> //needs to go to /PeoplePods/pods/core_files/index.php?id=$1&size=$2  [QSA,L] # core_files
    route("/files", "files") -> 
    route("/friends", "friends") ->
    route("/feeds/:args", "feeds") -> //needs to go to /PeoplePods/pods/core_feeds/feed.php?args=$1 [QSA,L] # core_feeds
    route("/feeds", "feeds") -> //needs to go to /PeoplePods/pods/core_feeds/feed.php   [QSA,L] # core_feeds
    route("/lists/:args", "listFeeds") -> //needs to go to /PeoplePods/pods/core_feeds/list.php?args=$1 [QSA,L] # core_feeds
    route("/lists", "listFeeds") -> //needs to go to /PeoplePods/pods/core_feeds/list.php   [QSA,L] # core_feeds
    route("/groups", "groups") -> 
    route("/groups/:stub/:command", "groups") -> //needs to go to /PeoplePods/pods/core_groups/group.php?stub=$1&command=$2 [QSA,L] # core_groups
    route("/groups/:stub", "groups") -> //needs to go to /PeoplePods/pods/core_groups/group.php?stub=$1 [QSA,L] # core_groups
    route("/groups", "groups") -> //needs to go to /PeoplePods/pods/core_groups/index.php   [QSA,L] # core_groups
    route("/invite", "invite") -> //needs to go to /PeoplePods/pods/core_invite/index.php   [QSA,L] # core_invite
    route("/pages", "pages") -> 
    route("/pages/:stub", "view") -> //needs to go to /PeoplePods/pods/core_pages/view.php?stub=$1  [QSA,L] # core_pages
    route("/patients", "patients") -> 
    route("/pm", "private_messaging") -> 
    route("/inbox/conversationwith/:username", "conversation") -> //needs to go to /PeoplePods/pods/core_private_messaging/thread.php?username=$1   [QSA,L] # core_private_messaging
    route("/inbox", "inbox") -> //needs to go to /PeoplePods/pods/core_private_messaging/inbox.php  [QSA,L] # core_private_messaging
    route("/people/:username", "profile") -> //needs to go to /PeoplePods/pods/core_profiles/profile.php?username=$1    [QSA,L] # core_profiles
    route("/editprofile", "editProfile") -> //needs to go to /PeoplePods/pods/core_profiles/editprofile.php [QSA,L] # core_profiles
    route("/search", "search") -> //needs to go to /PeoplePods/pods/core_search/search.php  [QSA,L] # core_search
    route("/content", "user_content") -> 
    route("/dashboard/:healer", "healer_dashboard") -> //fixme work out this path and its handling
    route("/fb", "fb_connect") -> 
    route("/gravatars", "gravatars") -> 
    route("/landing_page", "landing_page") -> 
    route("/openid/:mode", "openId") -> //needs to go to /PeoplePods/pods/openid_connect/index.php?mode=$1  [QSA,L] # openid_connect
    route("/openid", "openId") -> //needs to go to /PeoplePods/pods/openid_connect/index.php    [QSA,L] # openid_connect
    route("/placekitten", "placekitten") -> 
    route("/twitter", "twitter") -> 
    route("/friends/:mode", "friends") -> //needs to go to /PeoplePods/pods/core_friends/index.php?mode=$1  [QSA,L] # core_friends
    route("/friends", "friends") -> //needs to go to /PeoplePods/pods/core_friends/index.php    [QSA,L] # core_friends
    route("/admin/:id/", "admin") -> 
    route("/api", "api1") -> //needs to go to /PeoplePods/pods/core_api_simple/index_version1.php   [QSA,L] # core_api_simple
    route("/api/:whichOne/:method", "api2") -> //needs to go to /PeoplePods/pods/core_api_simple/index_version2.php?method=$1   [QSA,L] # core_api_simple
    route("/tos", "terms_of_service" )-> //cursory terms of service link
    route("/install", "install") -> //todo needs to go to /PeoplePods/install/, but only the first run though...
run();

**Comment by mattsah** [comment] 2012-11-25 06:33
@nickolasnikolic 

The #1 cause of this is generally because there are no valid routes and inevitably Moor attempts to call it's own internal 404 route.  At some point the default callback began to no longer match the required rules that Moor required a callback to be (i.e. public and if on a class, implementing the MoorAbstractController).  Since the default 404 does not validate, it throws a ConinueException outside of the catch that it was in previously.

This was fixed in the .inK fork:  https://github.com/dotink/moor

One of the things I'm confused about with regards to your routes is the callbacks you're providing.  Are these all function names or just placeholders for time being?  Even if you get the .inK version above, you would want to, I think, double check how your routes are getting called.  Functions would need to be included and defined first... I would suggest moving toward static classes at the least so you can use an autoloader.

**Comment by jeffturcotte** [comment] 2012-11-26 02:40
@nickolasnikolic Are those your final routes? as it is stated above, the sytax you are using looks incorrect. The router can route a url to a global function, but is that what you are trying to do? I'm a little lost by the htaccess-esque route comments. Also, setURLPrefix is meant to take a url string to prepend to the URL, not the callback. Is that what you are trying to do?

@mattsah How many backwards compatibility breaks does your fork have? Would be willing to pull in the whole thing, or just cherry pick some commits.

**Comment by jeffturcotte** [comment] 2012-11-26 03:28
Looks like all these issues are related to the not found callback problem. Which was resolved in 589003e8bcb83f6b999955c60c2a840527b444e2. 

Closing. Thanks all.

**Closed as completed by jeffturcotte** 2012-11-26 03:28 UTC

**Comment by mattsah** [comment] 2012-11-26 04:19
@jeffturcotte 

as for backwards compat breaks none to my knowledge if you are pulling the most recent commits.  Although a few behaviors differ.  First is the addition of base controller which was for static controllers.  Second is that run() will return the value returned by the action.
